# Generated by Django 3.0 on 2021-06-28 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category_name', models.CharField(choices=[('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4'), ('Category 6', 'Category 6'), ('Category 7', 'Category 7'), ('Category 8', 'Category 8'), ('Category 9', 'Category 9')], max_length=20)),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to=products.utils.product_directory_path))),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('product_price', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_view', to='products.Product')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
