# Generated by Django 3.0 on 2021-06-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210628_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='user',
        ),
    ]
